import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';
import registerServiceWorker from './registerServiceWorker';
import './util/setRem';
import './util/base.css';
import $ from 'jquery';
window.jQuery = $;
window.jquery = $;
ReactDOM.render(<App />, document.getElementById('root'));
registerServiceWorker();
